package zw.co.jugaad.jswitch.feigndto;

public enum TransactionTypes {
    CASHIN,
    CASHOUT,
    REGISTRATION,
    WALLET_TRANSFER,
    AGENT_TRANSFER,
    AGENT_WALLET_TO_BANK,
    SUBSCRIBER_WALLET_TO_BANK,
    SUBSCRIBER_BANK_TO_WALLET,
    DISBURSEMENT,
    AGENT_BANK_TO_WALLET,
    LOAN_TO_BANK,
    LOAN_DISBURSEMENT,
    PAYMENT,
    SETTLEMENT,
    ADJUSTMENT,
    ZIPIT_SEND,
    ZIPIT_RECIEVE,
    REVERSAL,
    BILL_PAYMENT,
    BALANCE_ENQUIRY,
    MERCHANT_WALLET_TO_BANK
}
