package zw.co.jugaad.jswitch.enums;

public enum ResponseCode {
    TRANSACTION_SUCCESSFUL("00"),
    REFER_TO_CARD_ISSUER("01"),
    REFER_TO_CARD_ISSUER_SPECIAL_CONDITIONS("02"),
    INVALID_MERCHANT("03"),
    PICKUP("04"),
    DO_NOT_HONOR("05"),
    ERROR("06"),
    DO_NOT_HONOR_SPECIAL_CONDITIONS("07"),
    HONOR_WITH_IDENTIFICATION("08"),
    REQUEST_IN_PROGRESS("09"),
    APPROVED_FOR_PARTIAL_AMOUNT("10"),
    APPROVED_VIP("11"),
    INVALID_TRANSACTION("12"),
    INVALID_AMOUNT("13"),
    INVALID_CARD_NUMBER("14"),
    NO_SUCH_ISSUER("15"),
    APPROVED_UPDATE_TRACK3("16"),
    CUSTOMER_CANCELLATION("17"),
    CUSTOMER_DISPUTE("18"),
    REENTER_TRANSACTION("19"),
    INVALID_RESPONSE("20"),
    NO_ACTION_TAKEN("21"),
    SUSPECTED_MALFUNCTION("22"),
    UNACCEPTABLE_TRANSACTION_FEE("23"),
    FILE_UPDATE_NOT_SUPPORTED_BY_RECEIVER("23"),
    UNABLE_TO_LOCATE_RECORD_ON_FILE("25"),
    FORMAT_ERROR("30"),
    COMPLETED_PARTIALLY("32"),
    EXPIRED_CARD("33"),
    SUSPECTED_FRAUD("34"),
    CARD_ACCEPTOR_CONTACT_ACQUIRER("35"),
    RESTRICTED_CARD("36"),
    ALLOWABLE_PIN_TRIES_EXCEEDED("38"),
    NO_CREDIT_AMOUNT("39"),
    LOST_CARD("41"),
    NO_UNIVERSAL_ACCOUNT("42"),
    STOLEN_CARD_PICK_UP("43"),
    NO_INVESTMENT_ACCOUNT("44"),
    NOT_SUFFICIENT_FUNDS("51"),
    NO_CHECKING_ACCOUNT("52"),
    NO_SAVINGS_ACCOUNT("53"),
    EXPIRED_CARDS("54"),
    INCORRECT_PIN("55"),
    NO_CARD_RECORD("56"),
    TRANSACTION_NOT_PERMITTED_TO_CARDHOLDER("57"),
    TRANSACTION_NOT_PERMITTED_TO_TERMINAL("58"),
    SUSPECTED_FRAUDS("59"),
    EXCEEDS_WITHDRAWAL_LIMIT("61"),
    RESTRICTED_CARDS("62"),
    SECURITY_VIOLATION("63"),
    ORIGINAL_AMOUNT_INCORRECT("64"),
    EXCEEDS_WITHDRAWAL_FREQUENCY_LIMIT("65"),
    HARD_CAPTURE("67"),
    RESPONSE_RECEIVED_TOO_LATE("68"),
    ALLOWABLE_NUMBER_OF_PIN_TRIES_EXCEEDED("75"),
    ISSUER_OR_SWITCH_INOPERATIVE("91"),
    TRANSACTION_CANNOT_BE_COMPLETED("93"),
    DUPLICATE_TRANSMISSION("94"),
    RECONCILE_ERROR("95"),
    SYSTEM_MALFUNCTION("96")

    ;

    public final String code;

    ResponseCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public static ResponseCode valueOfCode(String code) {
        for (ResponseCode e : values()) {
            if (e.code.equals(code)) {
                return e;
            }
        }
        return null;
    }
}
