//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.14 at 10:22:25 PM CAT 
//


package zw.co.jugaad.jswitch.field127;


import javax.xml.bind.annotation.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExtendedTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderDetails" type="{}CustomerDetail"/&gt;
 *         &lt;element name="ReceiverDetails" type="{}CustomerDetail"/&gt;
 *         &lt;element name="SourceOfFunds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TranPurposeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ResponseDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PayeeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ZipitSmart" type="{}ZipitSmartDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extendedTransactionType",
    "senderDetails",
    "receiverDetails",
    "sourceOfFunds",
    "tranPurposeCode",
    "responseDescription",
    "payeeName",
    "zipitSmart"
})
@XmlRootElement(name = "field127")
public class Field127 {

    @XmlElement(name = "ExtendedTransactionType")
    protected String extendedTransactionType;
    @XmlElement(name = "SenderDetails", required = true)
    protected CustomerDetail senderDetails;
    @XmlElement(name = "ReceiverDetails", required = true)
    protected CustomerDetail receiverDetails;
    @XmlElement(name = "SourceOfFunds")
    protected String sourceOfFunds;
    @XmlElement(name = "TranPurposeCode")
    protected String tranPurposeCode;
    @XmlElement(name = "ResponseDescription")
    protected String responseDescription;
    @XmlElement(name = "PayeeName")
    protected String payeeName;
    @XmlElement(name = "ZipitSmart")
    protected ZipitSmartDetail zipitSmart;

    /**
     * Gets the value of the extendedTransactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedTransactionType() {
        return extendedTransactionType;
    }

    /**
     * Sets the value of the extendedTransactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedTransactionType(String value) {
        this.extendedTransactionType = value;
    }

    /**
     * Gets the value of the senderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDetail }
     *     
     */
    public CustomerDetail getSenderDetails() {
        return senderDetails;
    }

    /**
     * Sets the value of the senderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDetail }
     *     
     */
    public void setSenderDetails(CustomerDetail value) {
        this.senderDetails = value;
    }

    /**
     * Gets the value of the receiverDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDetail }
     *     
     */
    public CustomerDetail getReceiverDetails() {
        return receiverDetails;
    }

    /**
     * Sets the value of the receiverDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDetail }
     *     
     */
    public void setReceiverDetails(CustomerDetail value) {
        this.receiverDetails = value;
    }

    /**
     * Gets the value of the sourceOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOfFunds() {
        return sourceOfFunds;
    }

    /**
     * Sets the value of the sourceOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOfFunds(String value) {
        this.sourceOfFunds = value;
    }

    /**
     * Gets the value of the tranPurposeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranPurposeCode() {
        return tranPurposeCode;
    }

    /**
     * Sets the value of the tranPurposeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranPurposeCode(String value) {
        this.tranPurposeCode = value;
    }

    /**
     * Gets the value of the responseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseDescription() {
        return responseDescription;
    }

    /**
     * Sets the value of the responseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseDescription(String value) {
        this.responseDescription = value;
    }

    /**
     * Gets the value of the payeeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * Sets the value of the payeeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeName(String value) {
        this.payeeName = value;
    }

    /**
     * Gets the value of the zipitSmart property.
     * 
     * @return
     *     possible object is
     *     {@link ZipitSmartDetail }
     *     
     */
    public ZipitSmartDetail getZipitSmart() {
        return zipitSmart;
    }

    /**
     * Sets the value of the zipitSmart property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZipitSmartDetail }
     *     
     */
    public void setZipitSmart(ZipitSmartDetail value) {
        this.zipitSmart = value;
    }

}
